version: "3.2"
services:
  gateway:
    image: nginx:latest
    # name: lnprivate-gateway
    hostname: lnprivate-gateway
    # restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d/:ro
      - ./certbot/conf:/etc/letsencrypt/:ro
        #- ./backend/public:/srv/public
      - ./public:/srv/lnprivate_network/:ro
        #- ./data/certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot/:ro
    ports:
      - 80:80
      - 443:443
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    networks:
      - proxy
  certbot:
    image: certbot/certbot:latest
    hostname: lnprivate-certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - proxy
networks:
  proxy:
    external: true

volumes:
  cache:
    driver: local

